# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Github\2021study\pyqt5\guessNum.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_guessNum(object):
    def setupUi(self, guessNum):
        guessNum.setObjectName("guessNum")
        guessNum.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(guessNum)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(170, 170, 389, 269))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)

        # self.horizontalLayout_2.addStretch(1)

        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()



        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.textBrowser)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.beginButton = QtWidgets.QPushButton(self.widget)
        self.beginButton.setObjectName("beginButton")
        self.verticalLayout.addWidget(self.beginButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.exitButton = QtWidgets.QPushButton(self.widget)
        self.exitButton.setObjectName("exitButton")
        self.verticalLayout.addWidget(self.exitButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        guessNum.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(guessNum)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        guessNum.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(guessNum)
        self.statusbar.setObjectName("statusbar")
        guessNum.setStatusBar(self.statusbar)

        self.retranslateUi(guessNum)

        # 信号槽
        self.beginButton.clicked.connect(self.updateText)
        self.lineEdit.editingFinished.connect(self.inputNum)
        self.exitButton.clicked.connect(guessNum.close)

        QtCore.QMetaObject.connectSlotsByName(guessNum)

    def retranslateUi(self, guessNum):
        _translate = QtCore.QCoreApplication.translate
        guessNum.setWindowTitle(_translate("guessNum", "MainWindow"))
        self.label.setText(_translate("guessNum", "请输入数字"))
        self.beginButton.setText(_translate("guessNum", "开始"))
        self.exitButton.setText(_translate("guessNum", "退出"))

    def updateText(self):
        pass

    def inputNum(self):
        pass