# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Github\2021study\pyqt5\MainWinSignal.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.closeWinBtm = QtWidgets.QPushButton(Form)
        self.closeWinBtm.setObjectName("closeWinBtm")
        self.verticalLayout.addWidget(self.closeWinBtm)

        self.retranslateUi(Form)
        self.closeWinBtm.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.closeWinBtm.setText(_translate("Form", "Close Window"))
